### ISSUE TITLE
postinstall fail

### ISSUE THREAD

**Issue by hiroqn** [ivan-kleshnin/html-to-hyperscript#3]
`./bin/install` is depend on `mocha`, but mocha is devDependencies .
when we install by npm , fail first time

**Comment by ivan-kleshnin** [comment]
Thanks for reporting. Latest Node versions are usable without Babel. So I'm going to remove `/bin/install` step entirely.

**Comment by ivan-kleshnin** [comment]
Fixed in 53db330
